# Generated by Django 3.1.4 on 2020-12-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20201209_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='added_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
